/* Generated by zlib-ng 2.3.3 CMake on MSVC x64: -DZLIB_COMPAT=OFF -DBUILD_SHARED_LIBS=OFF (other defaults). */
/* gzread_mangle.h.in -- gzgetc name mangling helper
 * This file undefines the macro from zlib.h/zlib-ng.h to allow the real
 * function to be defined in gzread.c. This is tricky because the prefix
 * is not known ahead of time, thus the need for sed or similar.
 */
#undef gzgetc
#undef zng_gzgetc
