/* Generated by zlib-ng 2.3.3 CMake on MSVC x64: -DZLIB_COMPAT=OFF -DBUILD_SHARED_LIBS=OFF (other defaults). */
/* zlib_name_mangling.h has been automatically generated from
 * zlib_name_mangling.h.empty because ZLIB_SYMBOL_PREFIX was NOT set.
 */

#ifndef ZLIB_NAME_MANGLING_H
#define ZLIB_NAME_MANGLING_H

#endif /* ZLIB_NAME_MANGLING_H */
